version: "3.7"

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      INFLUXDB_DB: "${INFLUXDB_DB}"
      INFLUXDB_ADMIN_USER: "admin"
      INFLUXDB_ADMIN_PASSWORD: "admin"
      INFLUXDB_TOKEN: "admin"
      DOCKER_INFLUXDB_INIT_ORG: "max"
      DOCKER_INFLUXDB_INIT_BUCKET: "max"
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${TELEGRAF_INFLUXDB_TOKEN}
      INFLUXDB_USERNAME: "max"
      INFLUXDB_PASSWORD: "maxim1rowing"
      INFLUXDB_URL: "http://influxdb:8086"

  telegraf:
    image: telegraf:alpine
    container_name: telegraf
    links:
      - influxdb
    depends_on:
      - influxdb
    volumes:
      # Mount for telegraf config
      - ./telegraf/mytelegraf.conf:/etc/telegraf/telegraf.conf
    #env_file:
    #  - ./influxv2.env
    environment:
      DOCKER_INFLUXDB_INIT_ORG: "max"
      DOCKER_INFLUXDB_INIT_BUCKET: "max"
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "admin"
      INFLUX_TOKEN: "mwSIjkuYAI0RQ-weYK5otcLEmgAStgY1izrz8etl0a3dm7rDj6qUxObUWggXjo21fh7O9UWMrLAW1-PCQ2NOvw=="
    ports:
      - '127.0.0.1:8125:8125/udp'

  app1:
    build:
      dockerfile: Dockerfile
      context: ./
    image: "${APP_IMAGE}:${APP_IMAGE_TAG}"
    container_name: "${APP_SERVICE}0"
    environment:
      APP_PORT_FROM: "${APP_PORT_FROM}"
      APP_PORT_TO: "${APP_PORT_TO}"
      APP_PORT: "${APP_PORT}"
      APP_HOST: "${APP_HOST}"
      APP_SERVICE: "${APP_SERVICE}"
      LOG_PATH: "${LOG_PATH}"
      LOG_NAME: "${LOG_NAME}"
      LOG_EXT: "${LOG_EXT}"
      INFLUXDB_TOKEN: "mwSIjkuYAI0RQ-weYK5otcLEmgAStgY1izrz8etl0a3dm7rDj6qUxObUWggXjo21fh7O9UWMrLAW1-PCQ2NOvw=="
      INFLUXDB_URL: "http://influxdb:8086"
    ports:
      - "${APP_PORT}:${APP_PORT}"
    tty: yes

  app2:
    build:
      dockerfile: Dockerfile
      context: ./
    image: "${APP_IMAGE}:${APP_IMAGE_TAG}"
    container_name: "${APP_SERVICE}1"
    environment:
      APP_PORT_FROM: "${APP_PORT_FROM}"
      APP_PORT_TO: "${APP_PORT_TO}"
      APP_PORT: "8201"
      APP_HOST: "${APP_HOST}"
      APP_SERVICE: "${APP_SERVICE}"
      LOG_PATH: "${LOG_PATH}"
      LOG_NAME: "${LOG_NAME}"
      LOG_EXT: "${LOG_EXT}"
      INFLUXDB_TOKEN: "mwSIjkuYAI0RQ-weYK5otcLEmgAStgY1izrz8etl0a3dm7rDj6qUxObUWggXjo21fh7O9UWMrLAW1-PCQ2NOvw=="
      INFLUXDB_URL: "http://influxdb:8086"
    ports:
      - "8201:8201"
    tty: yes

  app3:
    build:
      dockerfile: Dockerfile
      context: ./
    image: "${APP_IMAGE}:${APP_IMAGE_TAG}"
    container_name: "${APP_SERVICE}2"
    environment:
      APP_PORT_FROM: "${APP_PORT_FROM}"
      APP_PORT_TO: "${APP_PORT_TO}"
      APP_PORT: "8202"
      APP_HOST: "${APP_HOST}"
      APP_SERVICE: "${APP_SERVICE}"
      LOG_PATH: "${LOG_PATH}"
      LOG_NAME: "${LOG_NAME}"
      LOG_EXT: "${LOG_EXT}"
    ports:
      - "8202:8202"
    tty: yes

  app4:
    build:
      dockerfile: Dockerfile
      context: ./
    image: "${APP_IMAGE}:${APP_IMAGE_TAG}"
    container_name: "${APP_SERVICE}3"
    environment:
      APP_PORT_FROM: "${APP_PORT_FROM}"
      APP_PORT_TO: "${APP_PORT_TO}"
      APP_PORT: "8203"
      APP_HOST: "${APP_HOST}"
      APP_SERVICE: "${APP_SERVICE}"
      LOG_PATH: "${LOG_PATH}"
      LOG_NAME: "${LOG_NAME}"
      LOG_EXT: "${LOG_EXT}"
    ports:
      - "8203:8203"
    tty: yes

  app5:
    build:
      dockerfile: Dockerfile
      context: ./
    image: "${APP_IMAGE}:${APP_IMAGE_TAG}"
    container_name: "${APP_SERVICE}4"
    environment:
      APP_PORT_FROM: "${APP_PORT_FROM}"
      APP_PORT_TO: "${APP_PORT_TO}"
      APP_PORT: "8204"
      APP_HOST: "${APP_HOST}"
      APP_SERVICE: "${APP_SERVICE}"
      LOG_PATH: "${LOG_PATH}"
      LOG_NAME: "${LOG_NAME}"
      LOG_EXT: "${LOG_EXT}"
    ports:
      - "8204:8204"
    tty: yes

volumes:
  influxdb-storage: