version: "3.9"

services:
  node:
    build:
      dockerfile: Dockerfile
      context: ./
    image: "${APP_IMAGE}:${APP_IMAGE_TAG}"
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      NODE_COUNT: "${NODE_COUNT}"
      APP_PORT: "${APP_PORT}"
      APP_HOST: "${APP_HOST}"
      APP_SERVICE: "${APP_SERVICE}"
      LOG_PATH: "${LOG_PATH}"
      LOG_NAME: "${LOG_NAME}"
      LOG_EXT: "${LOG_EXT}"
    tty: yes
