// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/service.proto

package grpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MyMessage struct {
	ServiceID            int32    `protobuf:"varint,1,opt,name=ServiceID,proto3" json:"ServiceID,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MyMessage) Reset()         { *m = MyMessage{} }
func (m *MyMessage) String() string { return proto.CompactTextString(m) }
func (*MyMessage) ProtoMessage()    {}
func (*MyMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{0}
}

func (m *MyMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MyMessage.Unmarshal(m, b)
}
func (m *MyMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MyMessage.Marshal(b, m, deterministic)
}
func (m *MyMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MyMessage.Merge(m, src)
}
func (m *MyMessage) XXX_Size() int {
	return xxx_messageInfo_MyMessage.Size(m)
}
func (m *MyMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_MyMessage.DiscardUnknown(m)
}

var xxx_messageInfo_MyMessage proto.InternalMessageInfo

func (m *MyMessage) GetServiceID() int32 {
	if m != nil {
		return m.ServiceID
	}
	return 0
}

func (m *MyMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*MyMessage)(nil), "proto.MyMessage")
}

func init() {
	proto.RegisterFile("proto/service.proto", fileDescriptor_c33392ef2c1961ba)
}

var fileDescriptor_c33392ef2c1961ba = []byte{
	// 146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x03, 0xf3, 0x84, 0x58, 0xc1, 0x94,
	0x92, 0x33, 0x17, 0xa7, 0x6f, 0xa5, 0x6f, 0x6a, 0x71, 0x71, 0x62, 0x7a, 0xaa, 0x90, 0x0c, 0x17,
	0x67, 0x30, 0x44, 0x91, 0xa7, 0x8b, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x6b, 0x10, 0x42, 0x40, 0x48,
	0x82, 0x8b, 0x3d, 0x17, 0xa2, 0x50, 0x82, 0x49, 0x81, 0x51, 0x83, 0x33, 0x08, 0xc6, 0x35, 0x72,
	0x07, 0x19, 0x02, 0x55, 0x28, 0x64, 0xc5, 0xc5, 0x17, 0x9c, 0x9a, 0x97, 0x12, 0x94, 0x98, 0x97,
	0x12, 0x5c, 0x52, 0x94, 0x99, 0x97, 0x2e, 0x24, 0x00, 0xb1, 0x52, 0x0f, 0x6e, 0x91, 0x14, 0x86,
	0x88, 0x12, 0x83, 0x06, 0xa3, 0x01, 0xa3, 0x13, 0x7b, 0x14, 0xab, 0x7e, 0x7a, 0x51, 0x41, 0x72,
	0x12, 0x1b, 0x58, 0xde, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x0a, 0x8c, 0x47, 0x1f, 0xbb, 0x00,
	0x00, 0x00,
}
