apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
    tier: backend
    env: {{ .Values.environment }}
  name: api
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8000
    - name: grpc
      port: 10000
      protocol: TCP
      targetPort: 10000
    - name: metrics
      port: 9808
      protocol: TCP
      targetPort: 9808
  selector:
    app: api
